### ISSUE TITLE
Settings: Field mapping

### ISSUE THREAD

**Issue by darkshine0x** [darkshine0x/watchdog-custodian-checks#20]
At a first stage, the input data has to be loaded in a standardised way (fields, order, etc. are given). But in the future, there should be a more flexible way.

In order to accomplish that, there should be a possibility in the settings form to link object data fields to the input fields.

**Comment by jbaumann2** [comment]
**Decision**
There is going to be a set of possible checks. For each check, there will be UserControl in the Settings where the necessary fields have to defined.
