### ISSUE TITLE
Rule form: Implement update and deletion of rules

### ISSUE THREAD

**Issue by darkshine0x** [darkshine0x/watchdog-custodian-checks#40]

**Comment by jbaumann2** [comment]
Deletion commit 1404d51cac19ce38c4d8b4b5acb4d5fd5d206336

**Comment by darkshine0x** [comment]
**Update of rules**
The rule should be loaded in the same UI as at the insertion. The dropdown for the rule kind should be disabled however.

**Comment by darkshine0x** [comment]
**Note regarding the implementation**
The rule to be edited will be determined by the data bound item of the clicked rule label. The rule will then be passed to the corresponding user control. The submit actions are invoked normally, but there has to be a check, that if the passed rule is not equal to null, that no new rule should be created, but the values of the exisiting one should be updated.
